In [1]:
import numpy as np
import pandas as pd

In [2]:
train_x = np.load('train_x.npy')
train_y = np.load('train_y.npy')
test_x = np.load('test_x.npy')
test_y = np.load('test_y.npy')

In [3]:
train_x[0]

array([376.        , 158.        , 601.        , 177.        ,
       469.        , 154.        ,   1.7521161 ,   0.64675843,
         1.82179901])

In [4]:
train_y[0]

array([0, 0, 0, 0, 0, 1, 0, 0, 0])

In [5]:
train_y[20]

array([0, 0, 0, 1, 0, 0, 0, 0, 0])

In [6]:
train_y[100]

array([0, 0, 0, 0, 0, 1, 0, 0, 0])

In [10]:
train_y[21]

array([0, 0, 0, 0, 0, 1, 0, 0, 0])